export function IntroSection() {
  return <section className="intro shell section-space"><div><p className="eyebrow accent">The PrimeQuest standard</p><h2>Built for decisions<br /><em>that matter.</em></h2></div><div className="intro-copy"><p>We work between opportunity and action. Our role is to make the next step clearer, the conversation more direct and the process more considered.</p><a className="text-link dark-link" href="#process">Our approach <span>→</span></a></div></section>;
}

export function ProcessSection() {
  return <section className="process shell section-space" id="process"><div className="section-heading"><div><p className="eyebrow accent">A more useful process</p><h2>From first brief<br /><em>to clear next step.</em></h2></div><p>Every conversation begins with context. We qualify the requirement, confirm the opportunity and keep communication moving through one trusted channel.</p></div><div className="process-list"><div><span>01</span><h3>Tell us what you need</h3><p>Buyer inquiry, seller mandate or a broader brief.</p></div><div><span>02</span><h3>We qualify the fit</h3><p>Our team reviews the details and available routes.</p></div><div><span>03</span><h3>Move with confidence</h3><p>Receive a clear response and a practical next step.</p></div></div></section>;
}

export function FaqSection() {
  return <section className="faq-section section-space" id="faq"><div className="shell"><div className="section-heading"><div><p className="eyebrow accent">Questions, answered</p><h2>Before the<br /><em>conversation.</em></h2></div><p>Clear expectations make better introductions. These answers cover the most common questions across our vessel, property, land and agricultural work.</p></div><div className="faq-list"><details><summary>Are the vessel listings verified? <span>+</span></summary><p>Published listings are reviewed through PrimeQuest&apos;s process before they are made available. Verification means internal review of submitted information; it is not a legal guarantee of ownership or a substitute for independent due diligence.</p></details><details><summary>Can I submit a property or land mandate? <span>+</span></summary><p>Yes. Owners and authorized representatives can submit property, land, track farm and agricultural opportunities through the dedicated mandate page. Supporting documents remain private during review.</p></details><details><summary>How do buyer inquiries work? <span>+</span></summary><p>Tell us the category, location, budget, timing and requirements. PrimeQuest qualifies the brief and shares suitable opportunities through the appropriate contact channel.</p></details><details><summary>What information should a seller provide? <span>+</span></summary><p>Start with the asset title, location, asking terms, photos and any supporting ownership, title, survey, technical or permit documents relevant to the category.</p></details><details><summary>Does submitting a mandate guarantee publication? <span>+</span></summary><p>No. Every submission may be reviewed, edited, held for more information, rejected, suspended or removed. Submission does not guarantee a buyer or completed transaction.</p></details></div></div></section>;
}
