export const offerings = [
  { id: "vessels", number: "01", title: "Vessel brokerage", shortTitle: "Vessels", text: "Commercial, private and support vessels introduced with context and care.", heroTitle: "The right vessel.\nThe right route.", heroCopy: "Source a vessel, sell a vessel or place a private mandate. PrimeQuest keeps the route clear.", background: "https://images.unsplash.com/photo-1540946485063-a40da27545f8?auto=format&fit=crop&w=2200&q=80", sellerFields: "Vessel photos, specification sheet, registration or ownership documents where available.", mediaAccept: "image/jpeg,image/png,image/webp,application/pdf", documentLabel: "Vessel specifications / ownership documents" },
  { id: "energy", number: "02", title: "Oil & gas advisory", shortTitle: "Oil & gas", text: "Introductions and advisory support for serious energy opportunities.", heroTitle: "Energy with intent.\nA clearer route.", heroCopy: "Bring an energy mandate or a buyer brief. PrimeQuest qualifies the opportunity before an introduction.", background: "https://images.unsplash.com/photo-1513828583688-c52646db42da?auto=format&fit=crop&w=2200&q=80", sellerFields: "Asset photos, technical summary, permits, title or operating documents where available.", mediaAccept: "image/jpeg,image/png,image/webp,application/pdf", documentLabel: "Technical, title or permit documents" },
  { id: "property", number: "03", title: "Property & land", shortTitle: "Property & land", text: "Property, land and development opportunities for genuine buyers and owners.", heroTitle: "A place to build.\nA better way forward.", heroCopy: "Share a property or land mandate or a buyer brief. PrimeQuest helps make the next step clear.", background: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=2200&q=80", sellerFields: "Property photos, survey plan, title documents and location details where available.", mediaAccept: "image/jpeg,image/png,image/webp,application/pdf", documentLabel: "Survey, title or ownership documents" },
  { id: "agriculture", number: "04", title: "Agriculture & track farms", shortTitle: "Agriculture", text: "Land, track farms and agricultural opportunities prepared for the next conversation.", heroTitle: "Ground with purpose.\nRoom to grow.", heroCopy: "Place an agricultural asset or share a buyer brief. PrimeQuest prepares the conversation with care.", background: "https://images.unsplash.com/photo-1500076656116-558758c991c1?auto=format&fit=crop&w=2200&q=80", sellerFields: "Land photos, access information, survey plan, title documents and farm details where available.", mediaAccept: "image/jpeg,image/png,image/webp,application/pdf", documentLabel: "Survey, title or farm documents" },
] as const;

export type Offering = (typeof offerings)[number];
export type OfferingId = Offering["id"];
